# Generated by Django 3.1.7 on 2021-02-19 18:25

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Manutencoes', '0001_initial'),
        ('Veiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisicoes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50, verbose_name='Título da requisição')),
                ('data', models.DateField(verbose_name='Data da requisição')),
                ('requisicao', tinymce.models.HTMLField(verbose_name='Requisição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Manutencoes.local', verbose_name='Local do abastecimento')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Veiculos.veiculo')),
            ],
            options={
                'verbose_name': 'Requisição',
                'verbose_name_plural': 'Requisições',
            },
        ),
    ]
