# Generated by Django 3.1.5 on 2021-01-29 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('sobre_nome', models.CharField(max_length=50, verbose_name='Sobre nome')),
                ('email', models.CharField(max_length=70, verbose_name='Email')),
            ],
        ),
    ]
