# Generated by Django 3.1.5 on 2021-02-04 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadastrarVeiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo_veiculo', models.CharField(max_length=50, verbose_name='Modelo do veículo')),
                ('placa_veiculo', models.CharField(max_length=10, verbose_name='Placa do veículo')),
                ('ano_veicuo', models.IntegerField(verbose_name='Ano do veículo')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('imagem', models.ImageField(blank=True, upload_to='img', verbose_name='Imagem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
