# Generated by Django 3.1.5 on 2021-02-19 15:02

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abastecimento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField(verbose_name='Data do abastecimento')),
                ('valor_litro', models.DecimalField(decimal_places=2, max_digits=100000, verbose_name='Valor por litro')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=100000, verbose_name='Valor total do abastecimento')),
                ('imagem', models.ImageField(blank=True, upload_to='img', verbose_name='Imagem')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Abastecimento',
                'verbose_name_plural': 'Abastecimentos',
            },
        ),
        migrations.CreateModel(
            name='CadastrarProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('imagem', models.ImageField(blank=True, upload_to='img', verbose_name='Imagem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cadastrar produto',
                'verbose_name_plural': 'Cadastrar produtos',
            },
        ),
        migrations.CreateModel(
            name='CadastrarVeiculo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('placa_veiculo', models.CharField(max_length=10, verbose_name='Placa do veículo')),
                ('ano_veicuo', models.IntegerField(verbose_name='Ano do veículo')),
                ('tipo', models.CharField(choices=[('LEVE', 'LEVE'), ('MÉDIO', 'MÉDIO'), ('PESADO', 'PESADO')], default='LEVE', max_length=10, verbose_name='Tipo')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('imagem', models.ImageField(blank=True, upload_to='img', verbose_name='Imagem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cadastrar veículo',
                'verbose_name_plural': 'Cadastrar veículos',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50, verbose_name='Categoria')),
                ('imagem', models.ImageField(blank=True, upload_to='img', verbose_name='Imagem')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50, verbose_name='Fabricante')),
                ('imagem', models.ImageField(blank=True, upload_to='img', verbose_name='Imagem')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fabricante',
                'verbose_name_plural': 'Fabricantes',
            },
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50, verbose_name='Local')),
                ('cnpj', models.CharField(blank=True, max_length=50, verbose_name='CNPJ')),
                ('imagem', models.ImageField(blank=True, upload_to='img', verbose_name='Imagem')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Local',
                'verbose_name_plural': 'Locais',
            },
        ),
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=100000, verbose_name='Valor da manutenção')),
                ('data', models.DateField(verbose_name='Data da manutenção')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('imagem', models.ImageField(blank=True, upload_to='img', verbose_name='Imagem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.local', verbose_name='Local da manutenção')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.cadastrarveiculo')),
            ],
            options={
                'verbose_name': 'Manutenção',
                'verbose_name_plural': 'Manutenções',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50, verbose_name='Marca')),
                ('imagem', models.ImageField(blank=True, upload_to='img', verbose_name='Imagem')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
            },
        ),
        migrations.CreateModel(
            name='ModeloVeiculo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50, verbose_name='Modelo do veículo')),
                ('imagem', models.ImageField(blank=True, upload_to='img', verbose_name='Imagem')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Modelo do veículo',
                'verbose_name_plural': 'Modelos dos veículos',
            },
        ),
        migrations.CreateModel(
            name='Posto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50, verbose_name='Posto')),
                ('imagem', models.ImageField(blank=True, upload_to='img', verbose_name='Imagem')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Posto',
                'verbose_name_plural': 'Postos',
            },
        ),
        migrations.CreateModel(
            name='Requisicoes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50, verbose_name='Título da requisição')),
                ('data', models.DateField(verbose_name='Data da requisição')),
                ('requisicao', tinymce.models.HTMLField(verbose_name='Requisição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.local')),
            ],
            options={
                'verbose_name': 'Requisição',
                'verbose_name_plural': 'Requisições',
            },
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50, verbose_name='Responsável')),
                ('imagem', models.ImageField(blank=True, upload_to='img', verbose_name='Imagem')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Responsável',
                'verbose_name_plural': 'Responsáveis',
            },
        ),
        migrations.CreateModel(
            name='TipoServico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servico', models.CharField(max_length=50, verbose_name='Serviço')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=100000, verbose_name='Valor do serviço')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('manutencao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.manutencao')),
            ],
            options={
                'verbose_name': 'Tipo de serviço',
                'verbose_name_plural': 'Tipos de serviços',
            },
        ),
        migrations.CreateModel(
            name='UnidadeMedida',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unidade_medida', models.CharField(max_length=50, verbose_name='Unidade de medida')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Unidade de medida',
                'verbose_name_plural': 'Unidade de medida',
            },
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50, verbose_name='Veiculo')),
                ('imagem', models.ImageField(blank=True, upload_to='img', verbose_name='Imagem')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
            },
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.RemoveField(
            model_name='produto',
            name='preco',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='quantidade',
        ),
        migrations.AddField(
            model_name='produto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2020-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='img', verbose_name='Imagem'),
        ),
        migrations.AddField(
            model_name='produto',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='requisicoes',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.veiculo'),
        ),
        migrations.AddField(
            model_name='cadastrarveiculo',
            name='fabricante_veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.fabricante'),
        ),
        migrations.AddField(
            model_name='cadastrarveiculo',
            name='modelo_veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.modeloveiculo'),
        ),
        migrations.AddField(
            model_name='cadastrarveiculo',
            name='nome_veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.veiculo'),
        ),
        migrations.AddField(
            model_name='cadastrarveiculo',
            name='responsavel',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='core.responsavel'),
        ),
        migrations.AddField(
            model_name='cadastrarproduto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.categoria'),
        ),
        migrations.AddField(
            model_name='cadastrarproduto',
            name='marca_produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.marca'),
        ),
        migrations.AddField(
            model_name='cadastrarproduto',
            name='nome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.produto'),
        ),
        migrations.AddField(
            model_name='cadastrarproduto',
            name='unidade_de_medida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unidademedida'),
        ),
        migrations.AddField(
            model_name='abastecimento',
            name='posto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.posto'),
        ),
        migrations.AddField(
            model_name='abastecimento',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.cadastrarveiculo'),
        ),
    ]
