# Generated by Django 3.1.5 on 2021-02-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cadastrarveiculo_fabricante_veiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2017-03-31 9:30:20'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='produto',
            name='fabricante_veiculo',
            field=models.CharField(default='2017-03-31 9:30:20', max_length=50, verbose_name='Fabricante do produto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='img', verbose_name='Imagem'),
        ),
        migrations.AddField(
            model_name='produto',
            name='unidade_de_medida',
            field=models.CharField(default='2017-03-31 9:30:20', max_length=5, verbose_name='Unidade de medida'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cadastrarveiculo',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='cadastrarveiculo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='produto',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
