# Generated by Django 3.1.5 on 2021-02-15 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210215_0634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastrarproduto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='cadastrarproduto',
            name='marca_produto',
        ),
        migrations.RemoveField(
            model_name='cadastrarproduto',
            name='nome',
        ),
    ]
