# Generated by Django 3.1.5 on 2021-02-15 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210215_0639'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastrarproduto',
            name='categoria',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.categoria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cadastrarproduto',
            name='marca_produto',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.marca'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cadastrarproduto',
            name='nome',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.produto'),
            preserve_default=False,
        ),
    ]
