# Generated by Django 3.1.5 on 2021-02-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_abastecimento_posto'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoServico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_servico', models.CharField(max_length=50, verbose_name='Tipo do serviço')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='abastecimento',
            name='valor_litro',
            field=models.DecimalField(decimal_places=2, max_digits=100000, verbose_name='Valor por litro'),
        ),
        migrations.AlterField(
            model_name='abastecimento',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, max_digits=100000, verbose_name='Valor total do abastecimento'),
        ),
        migrations.AlterField(
            model_name='manutencao',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=100000, verbose_name='Valor da manutenção'),
        ),
        migrations.AddField(
            model_name='manutencao',
            name='tipo_servico',
            field=models.ManyToManyField(to='core.TipoServico'),
        ),
    ]
