# Generated by Django 3.1.5 on 2021-02-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210205_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiposervico',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100000, verbose_name='Valor'),
            preserve_default=False,
        ),
    ]
