# Generated by Django 3.1.5 on 2021-02-15 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210215_0640'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abastecimento',
            options={'verbose_name': 'Abastecimento', 'verbose_name_plural': 'Abastecimentos'},
        ),
        migrations.AlterModelOptions(
            name='cadastrarproduto',
            options={'verbose_name': 'Cadastrar produto', 'verbose_name_plural': 'Cadastrar produtos'},
        ),
        migrations.AlterModelOptions(
            name='cadastrarveiculo',
            options={'verbose_name': 'Cadastrar veículo', 'verbose_name_plural': 'Cadastrar veículos'},
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='fabricante',
            options={'verbose_name': 'Fabricante', 'verbose_name_plural': 'Fabricantes'},
        ),
        migrations.AlterModelOptions(
            name='local',
            options={'verbose_name': 'Local', 'verbose_name_plural': 'Locais'},
        ),
        migrations.AlterModelOptions(
            name='manutencao',
            options={'verbose_name': 'Manutenção', 'verbose_name_plural': 'Manutenções'},
        ),
        migrations.AlterModelOptions(
            name='marca',
            options={'verbose_name': 'Marca', 'verbose_name_plural': 'Marcas'},
        ),
        migrations.AlterModelOptions(
            name='modeloveiculo',
            options={'verbose_name': 'Modelo do veículo', 'verbose_name_plural': 'Modelos dos veículos'},
        ),
        migrations.AlterModelOptions(
            name='posto',
            options={'verbose_name': 'Posto', 'verbose_name_plural': 'Postos'},
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AlterModelOptions(
            name='requisicoes',
            options={'verbose_name': 'Requisição', 'verbose_name_plural': 'Requisições'},
        ),
        migrations.AlterModelOptions(
            name='responsavel',
            options={'verbose_name': 'Responsável', 'verbose_name_plural': 'Responsáveis'},
        ),
        migrations.AlterModelOptions(
            name='tiposervico',
            options={'verbose_name': 'Tipo de serviço', 'verbose_name_plural': 'Tipos de serviços'},
        ),
        migrations.AlterModelOptions(
            name='veiculo',
            options={'verbose_name': 'Veículo', 'verbose_name_plural': 'Veículos'},
        ),
    ]
