# Generated by Django 3.1.5 on 2021-02-15 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210215_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadeMedida',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unidade_medida', models.CharField(max_length=50, verbose_name='Unidade de medida')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Unidade de medida',
                'verbose_name_plural': 'Unidade de medida',
            },
        ),
        migrations.AlterField(
            model_name='cadastrarproduto',
            name='unidade_de_medida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unidademedida'),
        ),
    ]
