# Generated by Django 3.1.5 on 2021-02-15 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210215_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manutencao',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='manutencao',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.local', verbose_name='Local da manutenção'),
        ),
        migrations.RemoveField(
            model_name='manutencao',
            name='tipo_servico',
        ),
        migrations.AddField(
            model_name='manutencao',
            name='tipo_servico',
            field=models.CharField(default='', max_length=50, verbose_name='Tipo do serviço'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manutencao',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=100000, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='manutencao',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cadastrarveiculo'),
        ),
        migrations.DeleteModel(
            name='TipoServico',
        ),
    ]
