# Generated by Django 3.1.5 on 2021-02-15 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210215_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('idade', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='manutencao',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='manutencao',
            name='update_at',
        ),
        migrations.AlterField(
            model_name='manutencao',
            name='local',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.local', verbose_name='Local da manutenção'),
        ),
        migrations.AlterField(
            model_name='manutencao',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.cadastrarveiculo'),
        ),
        migrations.CreateModel(
            name='FilhoB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('idade', models.IntegerField()),
                ('pai', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.pai')),
            ],
        ),
        migrations.CreateModel(
            name='FilhoA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('idade', models.IntegerField()),
                ('pai', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.pai')),
            ],
        ),
    ]
