# Generated by Django 3.1.5 on 2021-02-16 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210215_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoServico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servico', models.CharField(max_length=50, verbose_name='Serviço')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=100000, verbose_name='Valor do serviço')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de serviço',
                'verbose_name_plural': 'Tipos de serviços',
            },
        ),
        migrations.RemoveField(
            model_name='filhob',
            name='pai',
        ),
        migrations.RemoveField(
            model_name='manutencao',
            name='tipo_servico',
        ),
        migrations.AddField(
            model_name='manutencao',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2020-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manutencao',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='manutencao',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='manutencao',
            name='local',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.local', verbose_name='Local da manutenção'),
        ),
        migrations.AlterField(
            model_name='manutencao',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=100000, verbose_name='Valor da manutenção'),
        ),
        migrations.AlterField(
            model_name='manutencao',
            name='veiculo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.cadastrarveiculo'),
        ),
        migrations.DeleteModel(
            name='FilhoA',
        ),
        migrations.DeleteModel(
            name='FilhoB',
        ),
        migrations.DeleteModel(
            name='Pai',
        ),
    ]
