# Generated by Django 3.1.5 on 2021-02-16 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210215_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiposervico',
            name='manutencao',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='core.manutencao'),
            preserve_default=False,
        ),
    ]
