# Generated by Django 3.1.5 on 2021-02-16 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_tiposervico_manutencao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiposervico',
            name='descricao',
        ),
    ]
