# Generated by Django 3.1.5 on 2021-02-16 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_tiposervico_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastrarveiculo',
            name='responsavel',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.responsavel'),
        ),
    ]
