# Generated by Django 3.1.5 on 2021-02-16 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210216_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastrarveiculo',
            name='fabricante_veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.fabricante'),
        ),
        migrations.AlterField(
            model_name='cadastrarveiculo',
            name='modelo_veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.modeloveiculo'),
        ),
        migrations.AlterField(
            model_name='cadastrarveiculo',
            name='nome_veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.veiculo'),
        ),
        migrations.AlterField(
            model_name='cadastrarveiculo',
            name='responsavel',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='core.responsavel'),
        ),
    ]
