# Generated by Django 3.1.7 on 2021-02-19 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Veiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50, verbose_name='Local')),
                ('cnpj', models.CharField(blank=True, max_length=50, verbose_name='CNPJ')),
                ('imagem', models.ImageField(blank=True, upload_to='img', verbose_name='Imagem')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Local',
                'verbose_name_plural': 'Locais',
            },
        ),
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=100000, verbose_name='Valor da manutenção')),
                ('data', models.DateField(verbose_name='Data da manutenção')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('imagem', models.ImageField(blank=True, upload_to='img', verbose_name='Imagem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Manutencoes.local', verbose_name='Local da manutenção')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Veiculos.cadastrarveiculo')),
            ],
            options={
                'verbose_name': 'Manutenção',
                'verbose_name_plural': 'Manutenções',
            },
        ),
        migrations.CreateModel(
            name='TipoServico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servico', models.CharField(max_length=50, verbose_name='Serviço')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=100000, verbose_name='Valor do serviço')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('manutencao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Manutencoes.manutencao')),
            ],
            options={
                'verbose_name': 'Tipo de serviço',
                'verbose_name_plural': 'Tipos de serviços',
            },
        ),
    ]
