# Generated by Django 3.1.7 on 2021-03-11 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manutencoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manutencao',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da manutenção'),
        ),
        migrations.AlterField(
            model_name='tiposervico',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do serviço'),
        ),
    ]
