# Generated by Django 3.1.7 on 2021-02-19 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Abastecimentos', '0002_auto_20210219_1525'),
        ('Produtos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manutencao',
            name='local',
        ),
        migrations.RemoveField(
            model_name='manutencao',
            name='veiculo',
        ),
        migrations.RemoveField(
            model_name='requisicoes',
            name='local',
        ),
        migrations.RemoveField(
            model_name='requisicoes',
            name='veiculo',
        ),
        migrations.RemoveField(
            model_name='tiposervico',
            name='manutencao',
        ),
        migrations.DeleteModel(
            name='CadastrarVeiculo',
        ),
        migrations.DeleteModel(
            name='Fabricante',
        ),
        migrations.DeleteModel(
            name='Local',
        ),
        migrations.DeleteModel(
            name='Manutencao',
        ),
        migrations.DeleteModel(
            name='ModeloVeiculo',
        ),
        migrations.DeleteModel(
            name='Requisicoes',
        ),
        migrations.DeleteModel(
            name='Responsavel',
        ),
        migrations.DeleteModel(
            name='TipoServico',
        ),
        migrations.DeleteModel(
            name='Veiculo',
        ),
    ]
