# Generated by Django 3.1.5 on 2021-02-04 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cadastrarveiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastrarveiculo',
            name='fabricante_veiculo',
            field=models.CharField(default='', max_length=50, verbose_name='Fabricante do veículo'),
            preserve_default=False,
        ),
    ]
