# Generated by Django 3.1.7 on 2021-02-19 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50, verbose_name='Fabricante')),
                ('imagem', models.ImageField(blank=True, upload_to='img', verbose_name='Imagem')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fabricante',
                'verbose_name_plural': 'Fabricantes',
            },
        ),
        migrations.CreateModel(
            name='ModeloVeiculo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50, verbose_name='Modelo do veículo')),
                ('imagem', models.ImageField(blank=True, upload_to='img', verbose_name='Imagem')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Modelo do veículo',
                'verbose_name_plural': 'Modelos dos veículos',
            },
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50, verbose_name='Responsável')),
                ('imagem', models.ImageField(blank=True, upload_to='img', verbose_name='Imagem')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Responsável',
                'verbose_name_plural': 'Responsáveis',
            },
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50, verbose_name='Veiculo')),
                ('imagem', models.ImageField(blank=True, upload_to='img', verbose_name='Imagem')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
            },
        ),
        migrations.CreateModel(
            name='CadastrarVeiculo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('placa_veiculo', models.CharField(max_length=10, verbose_name='Placa do veículo')),
                ('ano_veicuo', models.IntegerField(verbose_name='Ano do veículo')),
                ('tipo', models.CharField(choices=[('LEVE', 'LEVE'), ('MÉDIO', 'MÉDIO'), ('PESADO', 'PESADO')], default='LEVE', max_length=10, verbose_name='Tipo')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('imagem', models.ImageField(blank=True, upload_to='img', verbose_name='Imagem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('fabricante_veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Veiculos.fabricante')),
                ('modelo_veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Veiculos.modeloveiculo')),
                ('nome_veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Veiculos.veiculo')),
                ('responsavel', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='Veiculos.responsavel')),
            ],
            options={
                'verbose_name': 'Cadastrar veículo',
                'verbose_name_plural': 'Cadastrar veículos',
            },
        ),
    ]
