# Generated by Django 3.1.7 on 2021-02-19 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50, verbose_name='Posto')),
                ('imagem', models.ImageField(blank=True, upload_to='img', verbose_name='Imagem')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Posto',
                'verbose_name_plural': 'Postos',
            },
        ),
        migrations.CreateModel(
            name='Abastecimento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField(verbose_name='Data do abastecimento')),
                ('valor_litro', models.DecimalField(decimal_places=2, max_digits=100000, verbose_name='Valor por litro')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=100000, verbose_name='Valor total do abastecimento')),
                ('imagem', models.ImageField(blank=True, upload_to='img', verbose_name='Imagem')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('posto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Abastecimentos.posto')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Produtos.cadastrarveiculo')),
            ],
            options={
                'verbose_name': 'Abastecimento',
                'verbose_name_plural': 'Abastecimentos',
            },
        ),
    ]
