# Generated by Django 3.1.7 on 2021-03-11 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Veiculos', '0001_initial'),
        ('Abastecimentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abastecimento',
            name='valor_litro',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor por litro'),
        ),
        migrations.AlterField(
            model_name='abastecimento',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor total do abastecimento'),
        ),
        migrations.AlterField(
            model_name='abastecimento',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Veiculos.cadastrarveiculo'),
        ),
    ]
