# Generated by Django 3.1.7 on 2021-02-19 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Veiculos', '0001_initial'),
        ('Abastecimentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abastecimento',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Veiculos.cadastrarveiculo'),
        ),
    ]
