# Generated by Django 3.1.7 on 2021-03-11 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Fretes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mercadorias',
            name='fretes',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='Fretes.fretes'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mercadorias',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
